INSERT INTO EMPLOYEE (EMPLOYEE_ID, FIRSTNAME, LASTNAME, COUNTRY, EMPLOYEE_TYPE) VALUES (EMPLOYEE_ID_SEQUENCE.NEXTVAL,'PERNILLE', 'JACOBSEN', 'DENMARK', 'DELL mdf');
INSERT INTO EMPLOYEE (EMPLOYEE_ID, FIRSTNAME, LASTNAME, COUNTRY, EMPLOYEE_TYPE) VALUES (EMPLOYEE_ID_SEQUENCE.NEXTVAL,'Jeanette', 'Boring-Møller', 'DENMARK', 'DELL mdf');
INSERT INTO PARTNER (PARTNER_ID, COUNTRY, PARTNER_NAME, PARTNER_TYPE) VALUES (PARTNER_ID_SEQUENCE.NEXTVAL, 'DENMARK', 'JEANETTE', 'CPHBUSINESS');
INSERT INTO PARTNER (PARTNER_ID, COUNTRY, PARTNER_NAME, PARTNER_TYPE) VALUES (PARTNER_ID_SEQUENCE.NEXTVAL, 'DENMARK', 'Marta', 'valby');
INSERT INTO EMPLOYEE (EMPLOYEE_ID, FIRSTNAME, LASTNAME, COUNTRY, EMPLOYEE_TYPE) VALUES (EMPLOYEE_ID_SEQUENCE.NEXTVAL, 'DUMMY', 'DUMMY', 'DUMMY', 'DUMMY');
INSERT INTO PARTNER (PARTNER_ID, COUNTRY, PARTNER_NAME, PARTNER_TYPE) VALUES (PARTNER_ID_SEQUENCE.NEXTVAL, 'DUMMY', 'DUMMY', 'DUMMY');
INSERT INTO USERS (USER_ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, USER_TYPE, PARTNER_ID, EMPLOYEE_ID) VALUES (USER_ID_SEQUENCE.NEXTVAL, 'partner', 'partner', 'partner', 'partner', 'Partner', '1','0');
INSERT INTO USERS (USER_ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, USER_TYPE, PARTNER_ID, EMPLOYEE_ID) VALUES (USER_ID_SEQUENCE.NEXTVAL, 'dell', 'dell', 'dell', 'dell', 'dell', '0','1');
INSERT INTO QUARTER (QUARTER_NAME, QUARTER_BUDGET) VALUES ('FY1502', 500000);

INSERT INTO PROJECT (PROJECT_ID, STATUS, ACTIVITY_DESCRIPTION, COMMENTS, TARGET_AUDIENCE, PROJECT_BUDGET, PROJECT_COST, CURRENCY, START_DATE, END_DATE, OBJECTIVE_RESULT, REQUIRED_POE, PARTNER_ID, EMPLOYEE_ID, QUARTER_NAME) VALUES (9000, 'Project proposal', 'hello', 'hej', 'hi', 9000, 0, 'DKK', to_date('2014-04-28', YYYY-MM-DD), '2015-04-28', 'Nihou', 'Hola', 1, 1, 'FY1502');
INSERT INTO PROJECT (PROJECT_ID, STATUS, ACTIVITY_DESCRIPTION, COMMENTS, TARGET_AUDIENCE, PROJECT_BUDGET, PROJECT_COST, CURRENCY, START_DATE, END_DATE, OBJECTIVE_RESULT, REQUIRED_POE, PARTNER_ID, EMPLOYEE_ID, QUARTER_NAME) VALUES (9001, 'Project approval', 'Search project', 'Test2', 'hi', 9000, 0, 'DKK', '2014-04-28', '2015-04-28', 'Nihou', 'Hola', 1, 1, 'FY1502');
INSERT INTO PROJECT (PROJECT_ID, STATUS, ACTIVITY_DESCRIPTION, COMMENTS, TARGET_AUDIENCE, PROJECT_BUDGET, PROJECT_COST, CURRENCY, START_DATE, END_DATE, OBJECTIVE_RESULT, REQUIRED_POE, PARTNER_ID, EMPLOYEE_ID, QUARTER_NAME) VALUES (9002, 'Execution', 'Search project', 'hej', 'hi', 9000, 0, 'DKK', '2014-04-28', '2015-04-28', 'Nihou', 'Hola', 1, 1, 'FY1502');
INSERT INTO PROJECT (PROJECT_ID, STATUS, ACTIVITY_DESCRIPTION, COMMENTS, TARGET_AUDIENCE, PROJECT_BUDGET, PROJECT_COST, CURRENCY, START_DATE, END_DATE, OBJECTIVE_RESULT, REQUIRED_POE, PARTNER_ID, EMPLOYEE_ID, QUARTER_NAME) VALUES (9003, 'POE uploaded', 'Search project', 'hej', 'hi', 9000, 0, 'DKK', '2014-04-28', '2015-04-28', 'Nihou', 'Hola', 1, 1, 'FY1502');
INSERT INTO PROJECT (PROJECT_ID, STATUS, ACTIVITY_DESCRIPTION, COMMENTS, TARGET_AUDIENCE, PROJECT_BUDGET, PROJECT_COST, CURRENCY, START_DATE, END_DATE, OBJECTIVE_RESULT, REQUIRED_POE, PARTNER_ID, EMPLOYEE_ID, QUARTER_NAME) VALUES (9004, 'POE approved', 'Search project', 'hej', 'hi', 9000, 0, 'DKK', '2014-04-28', '2015-04-28', 'Nihou', 'Hola', 1, 1, 'FY1502');
INSERT INTO PROJECT (PROJECT_ID, STATUS, ACTIVITY_DESCRIPTION, COMMENTS, TARGET_AUDIENCE, PROJECT_BUDGET, PROJECT_COST, CURRENCY, START_DATE, END_DATE, OBJECTIVE_RESULT, REQUIRED_POE, PARTNER_ID, EMPLOYEE_ID, QUARTER_NAME) VALUES (9005, 'claim uploaded', 'Search project', 'hej', 'hi', 9000, 0, 'DKK', '2014-04-28', '2015-04-28', 'Nihou', 'Hola', 1, 1, 'FY1502');
INSERT INTO PROJECT (PROJECT_ID, STATUS, ACTIVITY_DESCRIPTION, COMMENTS, TARGET_AUDIENCE, PROJECT_BUDGET, PROJECT_COST, CURRENCY, START_DATE, END_DATE, OBJECTIVE_RESULT, REQUIRED_POE, PARTNER_ID, EMPLOYEE_ID, QUARTER_NAME) VALUES (9006, 'claim approved', 'Search project', 'hej', 'hi', 9000, 0, 'DKK', '2014-04-28', '2015-04-28', 'Nihou', 'Hola', 1, 1, 'FY1502');
INSERT INTO PROJECT (PROJECT_ID, STATUS, ACTIVITY_DESCRIPTION, COMMENTS, TARGET_AUDIENCE, PROJECT_BUDGET, PROJECT_COST, CURRENCY, START_DATE, END_DATE, OBJECTIVE_RESULT, REQUIRED_POE, PARTNER_ID, EMPLOYEE_ID, QUARTER_NAME) VALUES (9007, 'reimburse', 'Search project', 'hej', 'hi', 9000, 0, 'DKK', '2014-04-28', '2015-04-28', 'Nihou', 'Hola', 1, 1, 'FY1502');



commit;


