
Drop table QUARTER;
Drop table CONTACT_PERSON_PHONE;
Drop table PROJECT;
Drop table USERS;
Drop table PARTNER;
Drop table DELL_MARKETING;

Drop sequence PROJECT_ID_SEQUENCE;
Drop sequence USER_ID_SEQUENCE;
Drop sequence PARTNER_ID_SEQUENCE;
Drop sequence EMPLOYEE_ID_SEQUENCE;

Create Sequence EMPLOYEE_ID_SEQUENCE;
Create Sequence PARTNER_ID_SEQUENCE;
Create Sequence USER_ID_SEQUENCE;
Create Sequence PROJECT_ID_SEQUENCE;


Create table DELL_MARKETING(
EMPLOYEE_ID int PRIMARY KEY,
BUDGET int NOT NULL,
QUARTER VARCHAR2(6) NOT NULL
);

create table PARTNER(
PARTNER_ID INT,
COUNTRY VARCHAR2(10) NOT NULL,
PARTNER_NAME VARCHAR2(80) NOT NULL,
PARTNER_TYPE VARCHAR2(20) NOT NULL,
PRIMARY KEY (PARTNER_ID)
);

create table USERS(
USER_ID INT PRIMARY KEY,
USERNAME VARCHAR2(20) NOT NULL,
PASSWORD VARCHAR2(20) NOT NULL,
PARTNER_ID INT,
EMPLOYEE_ID INT,
FOREIGN KEY (PARTNER_ID) REFERENCES PARTNER,
FOREIGN KEY (EMPLOYEE_ID) REFERENCES DELL_MARKETING 
);


Create table PROJECT(
PROJECT_ID INT,
STATUS VARCHAR2(20) NOT NULL,
ACTIVITY_DESCRIPTION VARCHAR2(100) NOT NULL,
COMMENTS VARCHAR2(1000),
TARGET_AUDIENCE VARCHAR2(30) NOT NULL,
PROJECT_BUDGET INT NOT NULL,
PROJECT_COST INT,
CURRENCY VARCHAR2(4),
START_DATE DATE NOT NULL, 
END_DATE DATE NOT NULL,
OBJECTIVE_RESULT VARCHAR2(400) NOT NULL,
REQUIRED_POE VARCHAR2(400),
PARTNER_ID INT,
EMPLOYEE_ID INT,
PRIMARY KEY (PROJECT_ID),
FOREIGN KEY (PARTNER_ID) REFERENCES PARTNER,
FOREIGN KEY (EMPLOYEE_ID) REFERENCES DELL_MARKETING
);

create table CONTACT_PERSON_PHONE(
PARTNER_ID int PRIMARY KEY,
CONTACT_FIRST_NAME VARCHAR2(30) NOT NULL,
CONTACT_LAST_NAME VARCHAR2(30) NOT NULL,
CONTACT_PHONE VARCHAR2(20) NOT NULL
);

create table QUARTER(
QUARTER_NAME VARCHAR2(6) PRIMARY KEY
);

INSERT INTO DELL_MARKETING (EMPLOYEE_ID, BUDGET, QUARTER) VALUES (1, 50000, 'FY1502');
INSERT INTO PARTNER (PARTNER_ID, COUNTRY, PARTNER_NAME, PARTNER_TYPE) VALUES (1, 'DENMARK', 'JEANETTE', 'CPHBUSINESS');

commit;


